### ISSUE TITLE
4.11.0-beta2 PHP 8.1 - Changes in content are not reflected in search results

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-elemental#984]
The default pages (home, about, contact) are found in search results, but new pages or changes to content are not reflected in search results.

If changing content that is _not_ in an elemental block, the FullTextSearch Update Job message just says "[2022-05-16 14:43:05][INFO] All batched updates complete. Queuing commit job" after completion. The commit is created and runs fine, but the new content does not appear in search results.

If changing content that _is_ in an elemental block, or if running a full reindex, the output is a lot more verbose. I will include this in a comment below.

**Comment by GuySartorelli** [comment]
When running a full reindex or updating content in an elemental block, the output looks like the below. Note that this specific output was from a full reindex - the update of a single page has the same error output but excludes some of that begininng part.

> [2022-05-16 14:30:13] silverstripe\fulltextsearch\solr\reindex\jobs\solrreindexgroupqueuedjob.INFO: Beginning reindex group [] []
[2022-05-16 14:30:13] silverstripe\fulltextsearch\solr\reindex\jobs\solrreindexgroupqueuedjob.INFO: Adding SilverStripe\CMS\Model\SiteTree [] []
[2022-05-16 14:30:14] silverstripe\fulltextsearch\solr\reindex\jobs\solrreindexgroupqueuedjob.INFO: Updated 1,2,3,8,9,10,11,12,13,14,16,17,18,19 [] []
[2022-05-16 14:30:14] silverstripe\fulltextsearch\solr\reindex\jobs\solrreindexgroupqueuedjob.INFO: Done [] []
[2022-05-16 14:30:14] silverstripe\fulltextsearch\solr\reindex\jobs\solrreindexgroupqueuedjob.INFO: Queuing commit on all changes [] []
[2022-05-16 14:30:14] silverstripe\fulltextsearch\solr\reindex\jobs\solrreindexgroupqueuedjob.INFO: Completed reindex group [] []
    Exception: HTML Parse Error: Request handler Symbiote\QueuedJobs\Controllers\QueuedTaskRunner does not have a url_segment defined. Relying on this link may be an application error in /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/fulltextsearch/src/Search/Indexes/SearchIndex.php:502 Stack trace: #0 [internal function]: SilverStripe\FullTextSearch\Search\Indexes\SearchIndex->SilverStripe\FullTextSearch\Search\Indexes\{closure}() #1 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/RequestHandler.php(577): trigger_error() #2 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/dnadesign/silverstripe-elemental-userforms/src/Model/ElementForm.php(43): SilverStripe\Control\RequestHandler->Link() #3 [internal function]: DNADesign\ElementalUserForms\Model\ElementForm->Form() #4 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/View/ViewableData.php(485): call_user_func_array() #5 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/View/ViewableData.php(547): SilverStripe\View\ViewableData->obj() #6 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/View/SSViewer_Scope.php(323): SilverStripe\View\ViewableData->XML_val() #7 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/View/SSViewer_DataPresenter.php(309): SilverStripe\View\SSViewer_Scope->__call() #8 /tmp/silverstripe-cache-php8.1.4-var-www-mysite-releases-20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/www-data/.cachethemes.watea.templates.DNADesign.ElementalUserForms.Model.ElementForm.ss(22): SilverStripe\View\SSViewer_DataPresenter->__call() #9 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/View/SSViewer.php(602): include('...') #10 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/View/SSViewer.php(674): SilverStripe\View\SSViewer->includeGeneratedTemplate() #11 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/View/ViewableData.php(401): SilverStripe\View\SSViewer->process() #12 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/dnadesign/silverstripe-elemental/src/Models/BaseElement.php(527): SilverStripe\View\ViewableData->renderWith() #13 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/dnadesign/silverstripe-elemental/src/Models/BaseElement.php(509): DNADesign\Elemental\Models\BaseElement->forTemplate() #14 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/dnadesign/silverstripe-elemental/src/Extensions/ElementalPageExtension.php(59): DNADesign\Elemental\Models\BaseElement->getContentForSearchIndex() #15 [internal function]: DNADesign\Elemental\Extensions\ElementalPageExtension->getElementsForSearch() #16 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Core/Extensible.php(144): call_user_func_array() #17 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Core/CustomMethods.php(61): SilverStripe\View\ViewableData->SilverStripe\Core\{closure}() #18 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/fulltextsearch/src/Search/Indexes/SearchIndex.php(540): SilverStripe\View\ViewableData->__call() #19 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/fulltextsearch/src/Solr/SolrIndex.php(528): SilverStripe\FullTextSearch\Search\Indexes\SearchIndex->_getFieldValue() #20 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/fulltextsearch/src/Solr/SolrIndex.php(590): SilverStripe\FullTextSearch\Solr\SolrIndex->_addField() #21 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/fulltextsearch/src/Solr/SolrIndex.php(612): SilverStripe\FullTextSearch\Solr\SolrIndex->_addAs() #22 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/fulltextsearch/src/Solr/Reindex/Handlers/SolrReindexBase.php(201): SilverStripe\FullTextSearch\Solr\SolrIndex->add() #23 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/fulltextsearch/src/Solr/Reindex/Handlers/SolrReindexQueuedHandler.php(120): SilverStripe\FullTextSearch\Solr\Reindex\Handlers\SolrReindexBase->runGroup() #24 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/fulltextsearch/src/Solr/Reindex/Jobs/SolrReindexGroupQueuedJob.php(119): SilverStripe\FullTextSearch\Solr\Reindex\Handlers\SolrReindexQueuedHandler->runGroup() #25 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/symbiote/silverstripe-queuedjobs/src/Services/QueuedJobService.php(913): SilverStripe\FullTextSearch\Solr\Reindex\Jobs\SolrReindexGroupQueuedJob->process() #26 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/symbiote/silverstripe-queuedjobs/src/Services/QueuedJobService.php(1040): Symbiote\QueuedJobs\Services\QueuedJobService->Symbiote\QueuedJobs\Services\{closure}() #27 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/symbiote/silverstripe-queuedjobs/src/Services/QueuedJobService.php(1017): Symbiote\QueuedJobs\Services\QueuedJobService->withNestedState() #28 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/symbiote/silverstripe-queuedjobs/src/Tasks/ProcessJobQueueChildTask.php(30): Symbiote\QueuedJobs\Services\QueuedJobService->runJob() #29 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Dev/TaskRunner.php(127): Symbiote\QueuedJobs\Tasks\ProcessJobQueueChildTask->run() #30 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/RequestHandler.php(323): SilverStripe\Dev\TaskRunner->runTask() #31 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Controller.php(286): SilverStripe\Control\RequestHandler->handleAction() #32 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/RequestHandler.php(202): SilverStripe\Control\Controller->handleAction() #33 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Controller.php(212): SilverStripe\Control\RequestHandler->handleRequest() #34 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/RequestHandler.php(226): SilverStripe\Control\Controller->handleRequest() #35 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Controller.php(212): SilverStripe\Control\RequestHandler->handleRequest() #36 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Director.php(360): SilverStripe\Control\Controller->handleRequest() #37 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/tractorcow/silverstripe-fluent/src/Middleware/DetectLocaleMiddleware.php(116): SilverStripe\Control\Director->SilverStripe\Control\{closure}() #38 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/tractorcow/silverstripe-fluent/src/State/FluentState.php(152): TractorCow\Fluent\Middleware\DetectLocaleMiddleware->TractorCow\Fluent\Middleware\{closure}() #39 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/tractorcow/silverstripe-fluent/src/Middleware/DetectLocaleMiddleware.php(117): TractorCow\Fluent\State\FluentState->withState() #40 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): TractorCow\Fluent\Middleware\DetectLocaleMiddleware->process() #41 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/tractorcow/silverstripe-fluent/src/Middleware/InitStateMiddleware.php(52): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #42 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/tractorcow/silverstripe-fluent/src/State/FluentState.php(152): TractorCow\Fluent\Middleware\InitStateMiddleware->TractorCow\Fluent\Middleware\{closure}() #43 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/tractorcow/silverstripe-fluent/src/Middleware/InitStateMiddleware.php(53): TractorCow\Fluent\State\FluentState->withState() #44 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): TractorCow\Fluent\Middleware\InitStateMiddleware->process() #45 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/versioned/src/VersionedHTTPMiddleware.php(41): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #46 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Versioned\VersionedHTTPMiddleware->process() #47 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/subsites/src/Middleware/InitStateMiddleware.php(44): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #48 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Subsites\Middleware\InitStateMiddleware->process() #49 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/session-manager/src/Middleware/LoginSessionMiddleware.php(29): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #50 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\SessionManager\Middleware\LoginSessionMiddleware->process() #51 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/ConfirmationMiddleware.php(254): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #52 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\ConfirmationMiddleware->process() #53 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/ConfirmationMiddleware.php(254): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #54 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\ConfirmationMiddleware->process() #55 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Security/PasswordExpirationMiddleware.php(84): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #56 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Security\PasswordExpirationMiddleware->process() #57 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Security/BasicAuthMiddleware.php(68): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #58 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Security\BasicAuthMiddleware->process() #59 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Security/AuthenticationMiddleware.php(61): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #60 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Security\AuthenticationMiddleware->process() #61 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/testsession/src/TestSessionHTTPMiddleware.php(37): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #62 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\TestSession\TestSessionHTTPMiddleware->process() #63 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/akismet/src/Config/AkismetMiddleware.php(22): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #64 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Akismet\Config\AkismetMiddleware->process() #65 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/CanonicalURLMiddleware.php(190): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #66 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\CanonicalURLMiddleware->process() #67 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPCacheControlMiddleware.php(42): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #68 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\HTTPCacheControlMiddleware->process() #69 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/ChangeDetectionMiddleware.php(28): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #70 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\ChangeDetectionMiddleware->process() #71 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/FlushMiddleware.php(27): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #72 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\FlushMiddleware->process() #73 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/RequestProcessor.php(66): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #74 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\RequestProcessor->process() #75 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/hybridsessions/src/Control/HybridSessionMiddleware.php(18): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #76 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\HybridSessions\Control\HybridSessionMiddleware->process() #77 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/AllowedHostsMiddleware.php(60): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #78 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\AllowedHostsMiddleware->process() #79 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/TrustedProxyMiddleware.php(176): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #80 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\TrustedProxyMiddleware->process() #81 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/cwp/cwp-core/src/Control/InitialisationMiddleware.php(89): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #82 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): CWP\Core\Control\InitialisationMiddleware->process() #83 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(65): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}() #84 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Director.php(369): SilverStripe\Control\Director->callMiddleware() #85 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/HTTPApplication.php(117): SilverStripe\Control\Director->handleRequest() #86 [internal function]: SilverStripe\Control\HTTPApplication::SilverStripe\Control\{closure}() #87 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/HTTPApplication.php(136): call_user_func() #88 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(65): SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}() #89 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/HTTPApplication.php(137): SilverStripe\Control\HTTPApplication->callMiddleware() #90 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/src/Control/HTTPApplication.php(116): SilverStripe\Control\HTTPApplication->execute() #91 /var/www/mysite/releases/20220516114621_sc-aws-4_11_0-beta2-sink-p81-g3_tar_gz/vendor/silverstripe/framework/cli-script.php(33): SilverStripe\Control\HTTPApplication->handle() #92 {main} [] []
